FROM wordpress:php8.3-apache

RUN apt-get update \
 && apt-get install -y --no-install-recommends libicu-dev libonig-dev \
 && docker-php-ext-install intl mbstring \
 && curl -fsSL https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o /usr/local/bin/wp \
 && chmod +x /usr/local/bin/wp \
 && rm -rf /var/lib/apt/lists/*
